import { GlassButton } from "@/components/GlassButton";
import { GlassCard } from "@/components/GlassCard";
import { EmptyState as FeedbackEmptyState } from "@/components/feedback/EmptyState";
import { ScreenHeader } from "@/components/common/ScreenHeader";
import { MiniStat } from "@/components/common/MiniStat";
import type { AppScreen, ReviewQueueItem, StudyCard, QuizQuestion, WeakPoint, Lecture } from "@/types/lecture";

export function StudyHomeScreen({ cards, quizzes, queue, weakPoints, lectures, onGenerate, onNavigate, onBack }: { cards: StudyCard[]; quizzes: QuizQuestion[]; queue: ReviewQueueItem[]; weakPoints: WeakPoint[]; lectures: Lecture[]; onGenerate: () => void; onNavigate: (screen: AppScreen) => void; onBack: () => void }) {
  const todayCount = cards.filter((card) => card.status === "new" || card.status === "weak" || card.status === "later").length + queue.length;
  return <div className="space-y-5"><ScreenHeader eyebrow="Study" title="今日の復習" description="まずは「わからない」が付いた場所から復習しましょう。" onBack={onBack} /><GlassCard className="p-5"><div className="grid grid-cols-3 gap-2"><MiniStat label="今日" value={`${todayCount}`} /><MiniStat label="カード" value={`${cards.length}`} /><MiniStat label="小テスト" value={`${quizzes.length}`} /></div><div className="mt-4 grid gap-3"><GlassButton variant="primary" onClick={() => onNavigate("flashcards")}>復習カード開始</GlassButton><GlassButton onClick={() => onNavigate("quiz")}>小テスト開始</GlassButton><GlassButton onClick={() => onNavigate("examMode")}>テスト前モード</GlassButton></div></GlassCard><div className="grid grid-cols-2 gap-3"><GlassCard className="p-4"><h3 className="font-bold">未復習の講義</h3><p className="mt-2 text-3xl font-black">{lectures.filter((lecture) => lecture.summaryStatus === "not_started").length}</p></GlassCard><GlassCard className="p-4"><h3 className="font-bold">苦手項目</h3><p className="mt-2 text-3xl font-black">{weakPoints.length}</p></GlassCard></div><GlassCard solid className="p-4"><h3 className="text-lg font-bold">今日復習する項目</h3><div className="mt-3 space-y-2">{queue.slice(0, 5).length === 0 ? <FeedbackEmptyState title="まだ項目がありません" message="まだ復習が必要な講義はありません。" /> : queue.slice(0, 5).map((item) => <p key={item.id} className="rounded-2xl bg-slate-50 p-3 text-sm font-semibold text-slate-700">{item.title}: {item.description}</p>)}</div></GlassCard><div className="grid grid-cols-2 gap-3"><GlassButton onClick={onGenerate}>復習カード生成</GlassButton><GlassButton onClick={() => onNavigate("weakPoints")}>苦手ポイント</GlassButton><GlassButton onClick={() => onNavigate("reminders")}>リマインダー</GlassButton><GlassButton onClick={() => onNavigate("keyTerms")}>重要語句</GlassButton></div></div>;
}
